name: Publish and Release

on:
  push:
    branches:
      - main

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Make upload directory
        run: mkdir upload

      - name: Publish win-x64
        run: dotnet publish AvaloniaTool.Desktop -r win-x64 -c Release --sc /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true -o ./publish/win64

      - name: Zip win-x64
        run: |
          $files = Get-ChildItem -Path ./publish/win64/* -Recurse -Exclude *.pdb
          Compress-Archive -Path $files.FullName -DestinationPath ./upload/AvaloniaTool.Desktop.win-x64.zip

      - name: Enable Native AOT in .csproj
        run: |
          sed -i 's#<!--<PublishAot>true</PublishAot>-->#<PublishAot>true</PublishAot>#' AvaloniaTool.Desktop/AvaloniaTool.Desktop.csproj
          sed -i 's#<!--<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>-->#<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>#' AvaloniaTool.Desktop/AvaloniaTool.Desktop.csproj

      - name: Publish win-x64 AOT
        run: dotnet publish AvaloniaTool.Desktop -r win-x64 -c Release -o ./publish/win64-aot

      - name: Zip win-x64 AOT
        run: |
          $files = Get-ChildItem -Path ./publish/win64-aot/* -Recurse -Exclude *.pdb
          Compress-Archive -Path $files.FullName -DestinationPath ./upload/AvaloniaTool.Desktop.win-x64.NativeAOT.zip

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: windows
          path: ./upload

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Make upload directory
        run: mkdir upload

      - name: Publish linux-x64
        run: dotnet publish AvaloniaTool.Desktop -r linux-x64 -c Release --sc /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true -o ./publish/linux64

      - name: Zip linux-x64
        run: zip -r ./upload/AvaloniaTool.Desktop.linux-x64.zip ./publish/linux64 -x "*.pdb"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: linux
          path: ./upload

  android:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore Dependencies
        run: dotnet restore AvaloniaTool.Android

      - name: Publish Android
        run: dotnet publish AvaloniaTool.Android -c Release -f net9.0-android --no-restore -o ./publish

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: android
          path: ./publish/*Signed.apk

  release:
    runs-on: ubuntu-latest
    needs: [windows, linux, android]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./upload/**/*.zip
          tag_name: v${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
